name: Api Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate binary api
        run: ./gradlew clean apiCheck